# Generated by Django 5.2.4 on 2025-07-11 12:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
        ('categories', '0001_initial'),
        ('images', '0001_initial'),
        ('realisators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'user_ratings',
            },
        ),
        migrations.CreateModel(
            name='UserWatchlistMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_watchlist_movies',
            },
        ),
        migrations.CreateModel(
            name='ActorMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(db_column='id_actor', on_delete=django.db.models.deletion.CASCADE, to='actors.actor')),
            ],
            options={
                'db_table': 'actor_movies',
            },
        ),
        migrations.CreateModel(
            name='ImageMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(db_column='id_image', on_delete=django.db.models.deletion.CASCADE, to='images.image')),
            ],
            options={
                'db_table': 'image_movies',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id_movie', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('duration', models.DecimalField(decimal_places=2, help_text='Durée du film au format HH:MM', max_digits=4)),
                ('description', models.TextField(blank=True)),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('release_date', models.DateField()),
                ('average_rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actors', models.ManyToManyField(related_name='movies', through='movies.ActorMovie', to='actors.actor')),
                ('images', models.ManyToManyField(related_name='movies', through='movies.ImageMovie', to='images.image')),
            ],
            options={
                'db_table': 'movies',
            },
        ),
        migrations.AddField(
            model_name='imagemovie',
            name='movie',
            field=models.ForeignKey(db_column='id_movie', on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
        migrations.AddField(
            model_name='actormovie',
            name='movie',
            field=models.ForeignKey(db_column='id_movie', on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
        migrations.CreateModel(
            name='MovieCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.ForeignKey(db_column='id_categorie', on_delete=django.db.models.deletion.CASCADE, to='categories.categorie')),
                ('movie', models.ForeignKey(db_column='id_movie', on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
            options={
                'db_table': 'movie_categories',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(related_name='movies', through='movies.MovieCategorie', to='categories.categorie'),
        ),
        migrations.CreateModel(
            name='RealisatorMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(db_column='id_movie', on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('realisator', models.ForeignKey(db_column='id_realisator', on_delete=django.db.models.deletion.CASCADE, to='realisators.realisator')),
            ],
            options={
                'db_table': 'realisator_movies',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='realisators',
            field=models.ManyToManyField(related_name='movies', through='movies.RealisatorMovie', to='realisators.realisator'),
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(db_column='id_movie', on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
            options={
                'db_table': 'user_favorites',
            },
        ),
    ]
