# Generated by Django 5.2.4 on 2025-07-11 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavorite',
            name='user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrating',
            name='movie',
            field=models.ForeignKey(db_column='id_movie', on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
        migrations.AddField(
            model_name='userrating',
            name='user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userwatchlistmovie',
            name='movie',
            field=models.ForeignKey(db_column='id_movie', on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
        migrations.AddField(
            model_name='userwatchlistmovie',
            name='user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='imagemovie',
            unique_together={('movie', 'image')},
        ),
        migrations.AlterUniqueTogether(
            name='actormovie',
            unique_together={('movie', 'actor')},
        ),
        migrations.AlterUniqueTogether(
            name='moviecategorie',
            unique_together={('movie', 'categorie')},
        ),
        migrations.AlterUniqueTogether(
            name='realisatormovie',
            unique_together={('movie', 'realisator')},
        ),
        migrations.AlterUniqueTogether(
            name='userfavorite',
            unique_together={('user', 'movie')},
        ),
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together={('user', 'movie')},
        ),
        migrations.AlterUniqueTogether(
            name='userwatchlistmovie',
            unique_together={('user', 'movie')},
        ),
    ]
