# Generated by Django 5.2.4 on 2025-07-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('url', models.TextField()),
                ('is_main', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'images',
                'ordering': ['-is_main', 'name'],
            },
        ),
    ]
